# Generated by Django 3.1.7 on 2021-04-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20210418_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='status',
        ),
        migrations.AddField(
            model_name='todo',
            name='about',
            field=models.CharField(default='', max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='topic',
            field=models.CharField(choices=[('c', 'Course-link'), ('an', 'Announcement'), ('q1', 'Quiz-1'), ('q2', 'Quiz-2'), ('q3', 'Quiz-3'), ('a', 'Assignment'), ('p', 'Presentation'), ('q4', 'Extra-quiz'), ('m', 'Mid-exam'), ('f', 'Final-exam')], default='', max_length=2, null=True),
        ),
    ]
