# Generated by Django 3.1.7 on 2021-04-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_todo_release_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='release_date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='todo',
            name='course',
            field=models.CharField(choices=[('AI', 'AI'), ('CN', 'CN')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='topic',
            field=models.CharField(choices=[('Course-link', 'Course-link'), ('Announcement', 'Announcement'), ('Quiz-1', 'Quiz-1'), ('Quiz-2', 'Quiz-2'), ('Quiz-3', 'Quiz-3'), ('Extra-quiz', 'Extra-quiz'), ('Assignment', 'Assignment'), ('Presentation', 'Presentation'), ('Mid-exam', 'Mid-exam'), ('Final-exam', 'Final-exam')], max_length=15, null=True),
        ),
    ]
