# Generated by Django 3.1.7 on 2021-04-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_auto_20210418_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='about',
            field=models.TextField(default='', max_length=450, null=True),
        ),
    ]
