# Generated by Django 3.1.7 on 2021-04-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_auto_20210418_1623'),
    ]

    operations = [
        migrations.DeleteModel(
            name='about',
        ),
        migrations.DeleteModel(
            name='slider',
        ),
        migrations.AlterField(
            model_name='todo',
            name='about',
            field=models.TextField(max_length=450, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
