# Generated by Django 3.1.7 on 2021-04-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0015_auto_20210418_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='course',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='topic',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
