# Generated by Django 3.1.7 on 2021-04-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0017_auto_20210418_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='url1',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='url2',
            field=models.URLField(null=True),
        ),
    ]
