# Generated by Django 3.1.7 on 2021-04-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0018_auto_20210418_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='w1',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='w2',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
